library(stringr)
library(stringi)
library(data.table)
library(plyr)
library(magrittr)
library(dplyr)
library(ggplot2)
library(plotly)
library(leaflet)

source("data.preprocessing.R")
source("dividing.lines.to.chunks.R")
source("prepare.vehicles.raw.R")
source("format.data.R")
source("plot.speed.R")
